before_install: 
  - env
  - git clone https://github.com/okornev/cmsdal.git $TRAVIS_REPO_SLUG/../cmsdal
  - cd $TRAVIS_REPO_SLUG/../cmsdal 
  - mvn clean install -Dmaven.test.skip=true
  - cd ../..
  - git clone https://github.com/okornev/oo-commons.git $TRAVIS_REPO_SLUG/../oo-commons
  - cd $TRAVIS_REPO_SLUG/../oo-commons
  - mvn clean install -Dmaven.test.skip=true
sudo: false
language: java
jdk: oraclejdk8