shared:
  <<: *defaults
  authentication: ldap
#  authentication: database
  ldap_domain: homeoffice.wal-mart.com
  ldap_email_attribute: mail
  ldap_name_attribute: name

  session_inactivity_timeout: 999999

  host: localhost
  port: 3000
  protocol: http

  log_data_source: es

  policy_management: true
  check_policy_compliance: true

  omniauth:
    github:
      host: gecgithub01.walmart.com
      key: f73e3e58f4338764635a
      secret: 2e847224f34f37609343865fa6b44fcca0829fd5

  support_email: support@oneops.com
  news_url: https://confluence.walmart.com/x/-hgF
  help_url: https://confluence.walmart.com/x/EfwnAQ
  feedback_url: https://jira.walmart.com/secure/CreateIssue.jspa?pid=10132
  report_problem_url: https://jira.walmart.com/secure/CreateIssue.jspa?pid=10132&issuetype=10
  support_chat_url: https://walmartlabs.slack.com/messages/oneops/
  terms_of_service_url: http://www.oneops.com/legal/terms
  privacy_policy_url: http://corporate.walmart.com/privacy-security/walmart-privacy-policy

  asset_url: https://dfw-001-object-ocs.prod.walmart.com/v1/AUTH_16f78a1447394ba09679cb3471bf4f37/dev-1510/

  identity: stg@localhost
  cms_site: http://cms.stg-1407.core.oneops.prod.walmart.com:8080/
  events_site: http://sensor.stg-1407.core.oneops.prod.walmart.com:8080/
  metrics_site: http://daqws.stg-1407.core.oneops.prod.walmart.com:8080/
  notifications_site: http://antenna.stg-1407.core.oneops.prod.walmart.com:8080/
  search_site: http://search.stg-1407.core.oneops.prod.walmart.com:9200/
  log_site: http://eslogs.stg-1407.core.oneops.prod.walmart.com:9200/

#  identity: prod@localhost
#  cms_site: http://cmsapi.prod-1312.core.oneops.prod.walmart.com:8080/
#  events_site: http://sensor.prod-1312.core.oneops.prod.walmart.com:8080/
#  metrics_site: http://daqws.prod-1312.core.oneops.prod.walmart.com:8080/
#  notifications_site: http://antenna.prod-1312.core.oneops.prod.walmart.com:8080/
#  search_site: http://search.prod-1312.core.oneops.prod.walmart.com:9200/
#  log_site: http://eslogs.prod-1312.core.oneops.prod.walmart.com:9200/

#  identity: prod-mgmt@localhost
#  cms_site: http://cms.mgmt.oneops.walmart.com:8080/
#  events_site: http://sensor.mgmt.oneops.walmart.com:8080/
#  metrics_site: http://daqws.mgmt.oneops.walmart.com:8080/
#  notifications_site: http://antenna.mgmt.oneops.walmart.com:8080/
#  search_site: http://es.mgmt.oneops.walmart.com:9200/
#  log_site: http://es.mgmt.oneops.walmart.com:9200/

#  identity: int@localhost
#  cms_site: http://cms.int-1503.core.oneops.prod.walmart.com:8080/
#  events_site: http://sensor.int-1503.core.oneops.prod.walmart.com:8080/
#  metrics_site: http://cms.int-1503.core.oneops.prod.walmart.com:8080/
#  notifications_site: http://antenna.int-1503.core.oneops.prod.walmart.com:8080/
#  search_site: http://search.int-1503.core.oneops.prod.walmart.com:9200/
#  log_site: http://search.int-1503.core.oneops.prod.walmart.com:9200/

#  identity: qa@localhost
#  cms_site: http://cmsapi.qa-1312.core.oneops.qa.walmart.com:8080/
#  events_site: http://sensor.qa-1312.core.oneops.qa.walmart.com:8080/
#  metrics_site: http://cmsapi.qa-1312.core.oneops.qa.walmart.com:8080/
#  notifications_site: http://antenna.qa-1312.core.oneops.qa.walmart.com:8080/
#  search_site: http://search.qa-1312.core.oneops.qa.walmart.com:8080/
#  log_site: http://search.qa-1312.core.oneops.qa.walmart.com:8080/
#
#  identity: oo-dev@localhost
#  cms_site: http://cms.dev.oneops.walmart.com:8080/
#  events_site: http://sensor.dev.oneops.walmart.com:8080
#  metrics_site: http://cms.dev.oneops.walmart.com:8080
#  notifications_site: http://antenna.dev.oneops.walmart.com:8080
#  search_site: http://es.dev.oneops.walmart.com:9200
#  log_site: http://es.dev.oneops.walmart.com:9200


  mail_perform_deliveries: true
  smtp_address: sdc-vmta.walmart.com

# Example of overriding an existing section in 'settings.yml'
#development:
#  <<: *development
#  aaa: abc
#  authentication: yo
